 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/election_candidates", type: :request do
  
  # ElectionCandidate. As you add validations to ElectionCandidate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ElectionCandidate.create! valid_attributes
      get election_candidates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      election_candidate = ElectionCandidate.create! valid_attributes
      get election_candidate_url(election_candidate)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_election_candidate_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      election_candidate = ElectionCandidate.create! valid_attributes
      get edit_election_candidate_url(election_candidate)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ElectionCandidate" do
        expect {
          post election_candidates_url, params: { election_candidate: valid_attributes }
        }.to change(ElectionCandidate, :count).by(1)
      end

      it "redirects to the created election_candidate" do
        post election_candidates_url, params: { election_candidate: valid_attributes }
        expect(response).to redirect_to(election_candidate_url(ElectionCandidate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ElectionCandidate" do
        expect {
          post election_candidates_url, params: { election_candidate: invalid_attributes }
        }.to change(ElectionCandidate, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post election_candidates_url, params: { election_candidate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested election_candidate" do
        election_candidate = ElectionCandidate.create! valid_attributes
        patch election_candidate_url(election_candidate), params: { election_candidate: new_attributes }
        election_candidate.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the election_candidate" do
        election_candidate = ElectionCandidate.create! valid_attributes
        patch election_candidate_url(election_candidate), params: { election_candidate: new_attributes }
        election_candidate.reload
        expect(response).to redirect_to(election_candidate_url(election_candidate))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        election_candidate = ElectionCandidate.create! valid_attributes
        patch election_candidate_url(election_candidate), params: { election_candidate: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested election_candidate" do
      election_candidate = ElectionCandidate.create! valid_attributes
      expect {
        delete election_candidate_url(election_candidate)
      }.to change(ElectionCandidate, :count).by(-1)
    end

    it "redirects to the election_candidates list" do
      election_candidate = ElectionCandidate.create! valid_attributes
      delete election_candidate_url(election_candidate)
      expect(response).to redirect_to(election_candidates_url)
    end
  end
end
