 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/poll_workers", type: :request do
  
  # PollWorker. As you add validations to PollWorker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PollWorker.create! valid_attributes
      get poll_workers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      poll_worker = PollWorker.create! valid_attributes
      get poll_worker_url(poll_worker)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_poll_worker_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      poll_worker = PollWorker.create! valid_attributes
      get edit_poll_worker_url(poll_worker)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PollWorker" do
        expect {
          post poll_workers_url, params: { poll_worker: valid_attributes }
        }.to change(PollWorker, :count).by(1)
      end

      it "redirects to the created poll_worker" do
        post poll_workers_url, params: { poll_worker: valid_attributes }
        expect(response).to redirect_to(poll_worker_url(PollWorker.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PollWorker" do
        expect {
          post poll_workers_url, params: { poll_worker: invalid_attributes }
        }.to change(PollWorker, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post poll_workers_url, params: { poll_worker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested poll_worker" do
        poll_worker = PollWorker.create! valid_attributes
        patch poll_worker_url(poll_worker), params: { poll_worker: new_attributes }
        poll_worker.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the poll_worker" do
        poll_worker = PollWorker.create! valid_attributes
        patch poll_worker_url(poll_worker), params: { poll_worker: new_attributes }
        poll_worker.reload
        expect(response).to redirect_to(poll_worker_url(poll_worker))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        poll_worker = PollWorker.create! valid_attributes
        patch poll_worker_url(poll_worker), params: { poll_worker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested poll_worker" do
      poll_worker = PollWorker.create! valid_attributes
      expect {
        delete poll_worker_url(poll_worker)
      }.to change(PollWorker, :count).by(-1)
    end

    it "redirects to the poll_workers list" do
      poll_worker = PollWorker.create! valid_attributes
      delete poll_worker_url(poll_worker)
      expect(response).to redirect_to(poll_workers_url)
    end
  end
end
