 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/precincts", type: :request do
  
  # Precinct. As you add validations to Precinct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Precinct.create! valid_attributes
      get precincts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      precinct = Precinct.create! valid_attributes
      get precinct_url(precinct)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_precinct_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      precinct = Precinct.create! valid_attributes
      get edit_precinct_url(precinct)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Precinct" do
        expect {
          post precincts_url, params: { precinct: valid_attributes }
        }.to change(Precinct, :count).by(1)
      end

      it "redirects to the created precinct" do
        post precincts_url, params: { precinct: valid_attributes }
        expect(response).to redirect_to(precinct_url(Precinct.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Precinct" do
        expect {
          post precincts_url, params: { precinct: invalid_attributes }
        }.to change(Precinct, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post precincts_url, params: { precinct: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested precinct" do
        precinct = Precinct.create! valid_attributes
        patch precinct_url(precinct), params: { precinct: new_attributes }
        precinct.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the precinct" do
        precinct = Precinct.create! valid_attributes
        patch precinct_url(precinct), params: { precinct: new_attributes }
        precinct.reload
        expect(response).to redirect_to(precinct_url(precinct))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        precinct = Precinct.create! valid_attributes
        patch precinct_url(precinct), params: { precinct: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested precinct" do
      precinct = Precinct.create! valid_attributes
      expect {
        delete precinct_url(precinct)
      }.to change(Precinct, :count).by(-1)
    end

    it "redirects to the precincts list" do
      precinct = Precinct.create! valid_attributes
      delete precinct_url(precinct)
      expect(response).to redirect_to(precincts_url)
    end
  end
end
