 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/voters", type: :request do
  
  # Voter. As you add validations to Voter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Voter.create! valid_attributes
      get voters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      voter = Voter.create! valid_attributes
      get voter_url(voter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_voter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      voter = Voter.create! valid_attributes
      get edit_voter_url(voter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Voter" do
        expect {
          post voters_url, params: { voter: valid_attributes }
        }.to change(Voter, :count).by(1)
      end

      it "redirects to the created voter" do
        post voters_url, params: { voter: valid_attributes }
        expect(response).to redirect_to(voter_url(Voter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Voter" do
        expect {
          post voters_url, params: { voter: invalid_attributes }
        }.to change(Voter, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post voters_url, params: { voter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested voter" do
        voter = Voter.create! valid_attributes
        patch voter_url(voter), params: { voter: new_attributes }
        voter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the voter" do
        voter = Voter.create! valid_attributes
        patch voter_url(voter), params: { voter: new_attributes }
        voter.reload
        expect(response).to redirect_to(voter_url(voter))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        voter = Voter.create! valid_attributes
        patch voter_url(voter), params: { voter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested voter" do
      voter = Voter.create! valid_attributes
      expect {
        delete voter_url(voter)
      }.to change(Voter, :count).by(-1)
    end

    it "redirects to the voters list" do
      voter = Voter.create! valid_attributes
      delete voter_url(voter)
      expect(response).to redirect_to(voters_url)
    end
  end
end
